### ISSUE TITLE
Incorrect value is displayed in dynamic attribute browser for 'default value' column

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#53]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2626-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

TC:
create the project with dynamic attribute component
create entity
run app
admininstarion -> dynamic attributes
create category -> create attruibute with type = enum
enumeration -> edit -> add several values (1, 2, 3)
set default value =3
Save changes
ER: in Category Attributes table in column 'default value' should be value = 4
AR:
![image](https://user-images.githubusercontent.com/66992566/110954092-89afd380-8361-11eb-838c-3333a73aedc6.png)

**Comment by bulgakovea** [comment]
Fixed in #31

**Comment by owlet1997** [comment]
problem still exists
![image](https://user-images.githubusercontent.com/45730069/113273552-d0a04180-92ed-11eb-9979-e9500ba70d32.png)
